<a href="https://colab.research.google.com/github/Gaurang0053/Data-Science/blob/main/data_science(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
lst=np.array([10,20])
lst


array([10, 20])

In [ ]:
lst=np.zeros((2,3))
lst

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
lst=np.full((2,2),5)
lst

array([[5, 5],
       [5, 5]])

In [ ]:
lst=np.arange(10,20)
lst

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
lst = np.random.randint(1,100,5)
lst

array([93, 29, 48,  9, 44])

In [ ]:
lst=np.array([[10,20],[30,40]])
lst

array([[10, 20],
       [30, 40]])

In [ ]:
lst=np.array([[10,20],[30,60]])
lst.shape


(2, 2)

In [ ]:
x = np.array([3, 5, 7])
y = np.array([8, 6, 9])
np.vstack((x,y))



array([[3, 5, 7],
       [8, 6, 9]])

In [ ]:
x = np.array([3, 5, 7])
y = np.array([8, 6, 9])
np.hstack((x,y))



array([3, 5, 7, 8, 6, 9])

In [ ]:
arr1 = np.array([1, 1, 2, 3, 4]) 
arr2 = np.array([2, 1, 4, 6]) 
gfg = np.intersect1d(arr1, arr2)  
gfg 


array([1, 2, 4])

In [ ]:
arr1 = np.array([1, 1, 2, 3]) 
arr2 = np.array([2, 1, 4, 6]) 
gfg = np.setdiff1d(arr1, arr2)  
gfg 


array([3])

In [ ]:
arr1 = np.array([1, 1, 2, 3]) 
arr2 = np.array([2, 1, 4, 6]) 
gfg = np.add(arr1, arr2)  
gfg 


array([3, 2, 6, 9])

In [ ]:
a=np.array([10,20,30])
a=a+2
a

array([12, 22, 32])

In [ ]:
a=np.array([10,20,30])
a=a*2
a

array([20, 40, 60])

In [ ]:
a=np.array([10,20,30])
a=a/2
a

array([ 5., 10., 15.])